sudo: false
language: julia
os:
    - osx
    - linux

julia:
    - 0.7
    - 1.0
    - nightly

notifications:
    email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Dierckx")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
